"""Exercise the photo/teacher-scoping revision, not just Base.metadata.create_all.

Mirrors ``tests/test_biometric_migrations.py``: the SQLite round trip proves the
schema, the explicit constraint names, the ``ON DELETE SET NULL`` binding and the
data backfill; the offline PostgreSQL render proves the same revision compiles
for the production dialect (including dialect-correct boolean literals in the
backfill). Finally ``alembic check`` proves the models and the migrated schema
agree, so no drift is left behind.
"""
import io
from pathlib import Path

import sqlalchemy as sa
from alembic import command
from alembic.config import Config
from alembic.util import AutogenerateDiffsDetected

PREVIOUS_REVISION = "f9da2d24c61a"
SCOPING_REVISION = "0a3d991221bb"
REPO_ROOT = Path(__file__).resolve().parents[1]


def _config(**kwargs):
    config = Config(str(REPO_ROOT / "alembic.ini"), **kwargs)
    config.set_main_option("script_location", str(REPO_ROOT / "alembic"))
    return config


def _seed_pre_migration_rows(engine):
    """A tenant with one teacher account, one manager and a duplicated assignment."""
    with engine.begin() as connection:
        connection.execute(sa.text(
            "INSERT INTO private_schools (id, school_code, school_name, created_at) "
            "VALUES (1, 'PS', 'Photo Scoping School', CURRENT_TIMESTAMP)"
        ))
        connection.execute(sa.text(
            "INSERT INTO users (id, school_id, email, password_hash, role, first_name, last_name, "
            "staff_identifier, is_department_head, is_active, created_at) VALUES "
            "(7, 1, 'teacher@ps.edu.so', 'x', 'teacher', 'Scoping', 'Teacher', "
            "'NE-TID-2026-PS001', 0, 1, CURRENT_TIMESTAMP)"
        ))
        connection.execute(sa.text(
            "INSERT INTO users (id, school_id, email, password_hash, role, is_active, created_at) "
            "VALUES (8, 1, 'manager@ps.edu.so', 'x', 'school_manager', 1, CURRENT_TIMESTAMP)"
        ))
        connection.execute(sa.text(
            "INSERT INTO school_classes (id, school_id, class_level, stream, created_at) "
            "VALUES (3, 1, 5, 'A', CURRENT_TIMESTAMP), (4, 1, 5, 'B', CURRENT_TIMESTAMP)"
        ))
        connection.execute(sa.text(
            "INSERT INTO subjects (id, school_id, code, name, level, created_at) VALUES "
            "(11, 1, 'MAT-05', 'Mathematics', 5, CURRENT_TIMESTAMP), "
            "(12, 1, 'ENG-05', 'English', 5, CURRENT_TIMESTAMP)"
        ))
        # Same subject in two classrooms: the backfill must collapse it to one link.
        connection.execute(sa.text(
            "INSERT INTO teaching_assignments (school_id, teacher_id, class_id, subject_id, created_at) "
            "VALUES (1, 7, 3, 11, CURRENT_TIMESTAMP), (1, 7, 4, 11, CURRENT_TIMESTAMP)"
        ))
        connection.execute(sa.text(
            "INSERT INTO students (id, school_id, national_student_id, roll_number, first_name, "
            "last_name, gender, is_active, created_at) VALUES "
            "(21, 1, 'PS-21', 'PS-21', 'Existing', 'Student', 'Female', 1, CURRENT_TIMESTAMP)"
        ))


def test_photo_and_scoping_migration_sqlite_round_trip(tmp_path, monkeypatch):
    url = f"sqlite:///{tmp_path / 'photo_scoping.db'}"
    # Alembic-only override: never migrate the app's configured or shared test DB.
    monkeypatch.setenv("NE_EMIS_DATABASE_URL", url)
    config = _config()
    command.upgrade(config, PREVIOUS_REVISION)

    engine = sa.create_engine(url)

    @sa.event.listens_for(engine, "connect")
    def enable_foreign_keys(connection, _):
        connection.execute("PRAGMA foreign_keys=ON")

    try:
        _seed_pre_migration_rows(engine)
        command.upgrade(config, SCOPING_REVISION)

        inspector = sa.inspect(engine)

        # --- portrait columns -------------------------------------------
        students_photo = next(c for c in inspector.get_columns("students") if c["name"] == "photo_url")
        assert isinstance(students_photo["type"], sa.String)
        assert students_photo["type"].length == 500
        assert students_photo["nullable"] is True
        users_photo = next(c for c in inspector.get_columns("users") if c["name"] == "photo_url")
        assert users_photo["type"].length == 500 and users_photo["nullable"] is True

        # --- teachers: explicit constraint names -------------------------
        assert inspector.get_pk_constraint("teachers")["name"] == "pk_teachers"
        fks = {fk["name"]: fk for fk in inspector.get_foreign_keys("teachers")}
        assert fks["fk_teachers_school_id_private_schools"]["options"]["ondelete"] == "CASCADE"
        assert fks["fk_teachers_user_id_users"]["constrained_columns"] == ["user_id"]
        assert fks["fk_teachers_user_id_users"]["referred_table"] == "users"
        # Deleting a login must not delete the staff record.
        assert fks["fk_teachers_user_id_users"]["options"]["ondelete"] == "SET NULL"
        assert {u["name"] for u in inspector.get_unique_constraints("teachers")} == {
            "uq_teachers_school_email",
            "uq_teachers_staff_identifier",
        }
        indexes = {i["name"]: i for i in inspector.get_indexes("teachers")}
        assert indexes["ix_teachers_user_id"]["unique"] in (1, True)
        assert indexes["ix_teachers_school_id"]["unique"] in (0, False)

        # --- teacher_subjects -------------------------------------------
        assert inspector.get_pk_constraint("teacher_subjects")["name"] == "pk_teacher_subjects"
        ts_fks = {fk["name"]: fk for fk in inspector.get_foreign_keys("teacher_subjects")}
        assert set(ts_fks) == {
            "fk_teacher_subjects_teacher_id_teachers",
            "fk_teacher_subjects_subject_id_subjects",
            "fk_teacher_subjects_school_id_private_schools",
        }
        assert all(fk["options"]["ondelete"] == "CASCADE" for fk in ts_fks.values())
        assert [u["name"] for u in inspector.get_unique_constraints("teacher_subjects")] == [
            "uq_teacher_subject"
        ]

        # --- backfill ----------------------------------------------------
        with engine.connect() as connection:
            profiles = connection.execute(sa.text(
                "SELECT id, user_id, email, first_name, staff_identifier, is_active, photo_url FROM teachers"
            )).fetchall()
            assert len(profiles) == 1, "only the teacher account is backfilled"
            profile = profiles[0]
            assert profile.user_id == 7
            assert profile.email == "teacher@ps.edu.so"
            assert profile.staff_identifier == "NE-TID-2026-PS001"
            assert profile.is_active in (1, True)
            assert profile.photo_url is None

            links = connection.execute(sa.text(
                "SELECT teacher_id, subject_id, school_id, is_primary FROM teacher_subjects"
            )).fetchall()
            assert links == [(profile.id, 11, 1, 0)], "duplicate assignments collapse to one link"

            # Existing rows survive untouched.
            assert connection.execute(sa.text(
                "SELECT roll_number, photo_url FROM students"
            )).fetchall() == [("PS-21", None)]
            assert connection.execute(sa.text("PRAGMA foreign_key_check")).fetchall() == []

        # --- ON DELETE SET NULL ------------------------------------------
        metadata = sa.MetaData()
        users = sa.Table("users", metadata, autoload_with=engine)
        teachers = sa.Table("teachers", metadata, autoload_with=engine)
        with engine.begin() as connection:
            connection.execute(sa.text("DELETE FROM teaching_assignments"))
            connection.execute(sa.delete(users).where(users.c.id == 7))
            row = connection.execute(sa.select(teachers.c.id, teachers.c.user_id)).one()
            assert row.id == profile.id
            assert row.user_id is None, "teachers.user_id must be SET NULL, the profile survives"

        # --- downgrade / re-upgrade --------------------------------------
        command.downgrade(config, PREVIOUS_REVISION)
        downgraded = sa.inspect(engine)
        assert "teachers" not in downgraded.get_table_names()
        assert "teacher_subjects" not in downgraded.get_table_names()
        assert "photo_url" not in [c["name"] for c in downgraded.get_columns("students")]
        assert "photo_url" not in [c["name"] for c in downgraded.get_columns("users")]
        with engine.connect() as connection:
            assert connection.execute(sa.text("SELECT roll_number FROM students")).fetchall() == [("PS-21",)]

        command.upgrade(config, "head")
        with engine.connect() as connection:
            assert connection.execute(sa.text(
                "SELECT version_num FROM alembic_version"
            )).scalar() == SCOPING_REVISION

        # --- models and migrated schema agree ----------------------------
        command.check(config)
    except AutogenerateDiffsDetected as exc:  # pragma: no cover - failure path
        raise AssertionError(f"model/migration drift detected: {exc}") from exc
    finally:
        engine.dispose()


def test_photo_and_scoping_migration_compiles_for_postgresql(monkeypatch):
    # Offline SQL generation needs no running PostgreSQL server or credentials.
    monkeypatch.setenv("NE_EMIS_DATABASE_URL", "postgresql+psycopg2://localhost/photo_scoping_check")
    output = io.StringIO()
    config = _config(output_buffer=output)
    command.upgrade(config, f"{PREVIOUS_REVISION}:{SCOPING_REVISION}", sql=True)
    sql = output.getvalue()

    assert "CREATE TABLE teachers" in sql
    assert "id SERIAL NOT NULL" in sql
    assert "photo_url VARCHAR(500)" in sql
    assert "CONSTRAINT pk_teachers PRIMARY KEY (id)" in sql
    assert (
        "CONSTRAINT fk_teachers_user_id_users FOREIGN KEY(user_id) "
        "REFERENCES users (id) ON DELETE SET NULL"
    ) in sql
    assert (
        "CONSTRAINT fk_teachers_school_id_private_schools FOREIGN KEY(school_id) "
        "REFERENCES private_schools (id) ON DELETE CASCADE"
    ) in sql
    assert "CONSTRAINT uq_teachers_staff_identifier UNIQUE (staff_identifier)" in sql
    assert "CREATE UNIQUE INDEX ix_teachers_user_id ON teachers (user_id)" in sql
    assert "CREATE TABLE teacher_subjects" in sql
    assert "CONSTRAINT uq_teacher_subject UNIQUE (teacher_id, subject_id)" in sql
    assert "ALTER TABLE students ADD COLUMN photo_url VARCHAR(500)" in sql
    assert "ALTER TABLE users ADD COLUMN photo_url VARCHAR(500)" in sql

    # Backfill renders PostgreSQL boolean literals, never unrendered bind params.
    assert "COALESCE(u.is_department_head, false)" in sql
    assert "COALESCE(u.is_active, true)" in sql
    assert "INSERT INTO teacher_subjects" in sql
    assert "NULL, NULL" not in sql

    output.seek(0)
    output.truncate(0)
    command.downgrade(config, f"{SCOPING_REVISION}:{PREVIOUS_REVISION}", sql=True)
    downgrade_sql = output.getvalue()
    assert "ALTER TABLE users DROP COLUMN photo_url" in downgrade_sql
    assert "ALTER TABLE students DROP COLUMN photo_url" in downgrade_sql
    assert "DROP INDEX ix_teachers_user_id" in downgrade_sql
    assert "DROP TABLE teacher_subjects" in downgrade_sql
    assert "DROP TABLE teachers" in downgrade_sql
