"""add_classrooms_table

Revision ID: 9e350b087ca9
Revises: 6017c4a7f9d5
Create Date: 2026-09-05 10:31:32.504971
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e350b087ca9'
down_revision: Union[str, None] = '6017c4a7f9d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classrooms',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('grade_level', sa.String(length=50), nullable=False),
    sa.Column('academic_year', sa.String(length=20), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['private_schools.id'], name='fk_classrooms_school_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_classrooms')
    )
    with op.batch_alter_table('classrooms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_classrooms_academic_year'), ['academic_year'], unique=False)
        batch_op.create_index(batch_op.f('ix_classrooms_grade_level'), ['grade_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_classrooms_school_id'), ['school_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classrooms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_classrooms_school_id'))
        batch_op.drop_index(batch_op.f('ix_classrooms_grade_level'))
        batch_op.drop_index(batch_op.f('ix_classrooms_academic_year'))

    op.drop_table('classrooms')
    # ### end Alembic commands ###
