"""add_students_table

Revision ID: 494d928deaa7
Revises: 9e350b087ca9
Create Date: 2026-09-05 10:45:38.016802
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '494d928deaa7'
down_revision: Union[str, None] = '9e350b087ca9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('biometric_credentials', schema=None) as batch_op:
        batch_op.alter_column('student_id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)

    with op.batch_alter_table('biometric_verification_logs', schema=None) as batch_op:
        batch_op.alter_column('student_id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=True)

    with op.batch_alter_table('live_attendance', schema=None) as batch_op:
        batch_op.alter_column('student_id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)

    with op.batch_alter_table('student_grades', schema=None) as batch_op:
        batch_op.alter_column('student_id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)

    with op.batch_alter_table('student_invoices', schema=None) as batch_op:
        batch_op.alter_column('student_id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)

    # emis_id is NOT NULL: add it nullable first, backfill from the legacy
    # roll number / national id, then tighten the constraint.
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('emis_id', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('classroom_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('national_student_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('roll_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_students_classroom_id'), ['classroom_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_students_emis_id'), ['emis_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_students_school_id'), ['school_id'], unique=False)
        batch_op.create_foreign_key('fk_students_classroom_id', 'classrooms', ['classroom_id'], ['id'], ondelete='SET NULL')

    op.execute(
        "UPDATE students SET emis_id = COALESCE(roll_number, national_student_id, "
        "'NE-' || CAST(id AS VARCHAR)) WHERE emis_id IS NULL"
    )
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('emis_id', existing_type=sa.String(length=30), nullable=False)

    with op.batch_alter_table('subject_attendance', schema=None) as batch_op:
        batch_op.alter_column('student_id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subject_attendance', schema=None) as batch_op:
        batch_op.alter_column('student_id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint('fk_students_classroom_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_students_school_id'))
        batch_op.drop_index(batch_op.f('ix_students_emis_id'))
        batch_op.drop_index(batch_op.f('ix_students_classroom_id'))
        batch_op.alter_column('roll_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('national_student_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('classroom_id')
        batch_op.drop_column('emis_id')

    with op.batch_alter_table('student_invoices', schema=None) as batch_op:
        batch_op.alter_column('student_id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('student_grades', schema=None) as batch_op:
        batch_op.alter_column('student_id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('live_attendance', schema=None) as batch_op:
        batch_op.alter_column('student_id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('biometric_verification_logs', schema=None) as batch_op:
        batch_op.alter_column('student_id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('biometric_credentials', schema=None) as batch_op:
        batch_op.alter_column('student_id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
